from tap_zenefits.people_schema import People
from tap_zenefits.payruns_schema import Payruns
from tap_zenefits.pay_stubs_schema import PayStubs
from tap_zenefits.employments_schema import Employments
from tap_zenefits.departments_schema import Departments
from tap_zenefits.time_durations_schema import TimeDurations
